### ISSUE TITLE
(mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h)))这是不兼容嘛

### ISSUE THREAD

**Issue by nextkao** [leptos-null/classdumpctl#1]
(mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h)))

**Comment by leptos-null** [comment]
1. What operating system were you running on?
2. Did you compile from source, or did you download one of the pre-built binaries from <https://github.com/leptos-null/classdumpctl/releases>?
  a. if you compiled from source, what did you target?
  b. if you downloaded from releases, which one did you download?
3. What parameters did you pass to `classdumpctl`?

**Comment by leptos-null** [comment]
`classdumpctl` works by loading the requested mach-o image. This requires the mach-o image to have a slice with the same architecture as the `classdumpctl` that's running.

From this message, I'm guessing that you're running on macOS (`x86_64`) and trying to load a mach-o image that appears to be compiled for arm64 only.

In this case, these two are incompatible.

**Comment by nextkao** [comment]
下载的是 classdumpctl-mac版本
![2EC7F99D-C8BA-43E0-A976-1F7353D32CFE](https://github.com/leptos-null/classdumpctl/assets/104685849/d25c605b-fb10-4924-acb0-9b96dc88e8a2)

**Comment by leptos-null** [comment]
Thanks for the details. Yes, in this case, this Mach-O image will not be able to loaded, so it is incompatible.
https://github.com/0cyn/ktool may be helpful for what you're looking for.
